language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t modavids/docker-react -f Dockerfile.dev .
script:
    - docker run modavids/docker-react npm run test -- --coverage